### ISSUE TITLE
Weights license

### ISSUE THREAD

**Issue by nateraw** [mimbres/YourMT3#12]
Hi there, thanks a lot for this project!! ❤️ I played with your pre-release code/demo, everything looks great :).

I'm curious what the license for the model checkpoints are - do they match the code license or are you planning on making them a bit more open? 

Either way it sounds like folks can train their own and use their own ckpts commercially, right?

Thanks!

**Comment by mimbres** [comment]
Apache 2.0! This is `Your` MT3😄
