### ISSUE TITLE
Is inference time related to the type of musical instrument

### ISSUE THREAD

**Issue by an-old-guy-in-Ecust** [mimbres/YourMT3#17]
Is there any difference between the instrument type when inference? I found that when inference, the length of hearing is not proportional to the inference time. For example, when I use precision=16, bsz=8, model=YPTF+Single（noPS）, saxophone solo, which is 245s, needs 50s to infer, while the harp, which is 488s, needs 4.6s. Is this normal and why?

**Comment by mimbres** [comment]
@an-old-guy-in-Ecust Good catch! The main factor affecting inference time is the `number of tokens`. `Harp` is polyphonic, while `saxophone solo` is monophonic with longer average note lengths. As a result, `harp` music uses more tokens in 2 seconds, leading to longer decoding times. This is a known drawback of `autoregressive` decoders that decodes only a single token at each step.

For `bsz`, it’s more nuanced. For example, with `bsz=8`, a `20-second input` is split into `10x 2-second segments`, with 8 decoded in parallel first, followed by the remaining 2. **While a larger `bsz` might seem faster, it’s not always true.** The output sequence maxes at 1,024 tokens, and 80–90% is usually padded. Decoding stops early when `<EOS>` (end of sequence) appears for all batches, but with a larger `bsz`, this condition takes longer to meet, so bigger bsz isn’t always better!

**Comment by an-old-guy-in-Ecust** [comment]
Thanks for answering. So you mean harp should infer slower than saxophone but my result shows that harp is much faster. I tried five models you offered and difference precision, got the same result. 
For bsz, I understand. The key here is to find the best bsz which make each batch of audios as close in length as possible. But this bsz won't be best for all audios. There is no need to worry about which value to choose.

**Comment by an-old-guy-in-Ecust** [comment]
> `mber of tokens`. `Harp` is polyphonic, while `saxophone solo` is monophonic with longer average note lengths. As a result, `harp`

Thanks for answering. So you mean harp should infer slower than saxophone but my result shows that harp is much faster. I tried five models you offered and difference precision, got the same result.
For bsz, I understand. The key here is to find the best bsz which make each batch of audios as close in length as possible. But this bsz won't be best for all audios. There is no need to worry about which value to choose.

**Comment by an-old-guy-in-Ecust** [comment]
> @an-old-guy-in-Ecust Good catch! The main factor affecting inference time is the `number of tokens`. `Harp` is polyphonic, while `saxophone solo` is monophonic with longer average note lengths. As a result, `harp` music uses more tokens in 2 seconds, leading to longer decoding times. This is a known drawback of `autoregressive` decoders that decodes only a single token at each step.
> 
> For `bsz`, it’s more nuanced. For example, with `bsz=8`, a `20-second input` is split into `10x 2-second segments`, with 8 decoded in parallel first, followed by the remaining 2. **While a larger `bsz` might seem faster, it’s not always true.** The output sequence maxes at 1,024 tokens, and 80–90% is usually padded. Decoding stops early when `<EOS>` (end of sequence) appears for all batches, but with a larger `bsz`, this condition takes longer to meet, so bigger bsz isn’t always better!

Thanks for answering. So you mean harp should infer slower than saxophone but my result shows that harp is much faster. I tried five models you offered and difference precision, got the same result.
For bsz, I understand. The key here is to find the best bsz which make each batch of audios as close in length as possible. But this bsz won't be best for all audios. There is no need to worry about which value to choose.

**Comment by mimbres** [comment]
@an-old-guy-in-Ecust Oh, I didn’t read it properly. Is the saxophone taking longer? That’s really strange!

**Comment by an-old-guy-in-Ecust** [comment]
> @an-old-guy-in-Ecust Oh, I didn’t read it properly. Is the saxophone taking longer? That’s really strange!
[yourmt3_saxophone_test.zip](https://github.com/user-attachments/files/18101116/yourmt3_saxophone_test.zip)

Yes, the saxophone takes longer. Here's my saxophone test sample. maybe you could test it if you got time.

**Comment by an-old-guy-in-Ecust** [comment]
> @an-old-guy-in-Ecust Oh, I didn’t read it properly. Is the saxophone taking longer? That’s really strange!

[yourmt3_harp_test.zip](https://github.com/user-attachments/files/18101133/yourmt3_harp_test.zip)
harp test sample

**Comment by mimbres** [comment]
@an-old-guy-in-Ecust  
Hey! The harp_test file is symphony music performed by a full orchestra, and the saxophone_test is harp with a lot of reverb, right? This is very different from what I expected: saxophone-only sample vs. a harp-only sample. 

These are types of music that our training data might not cover, so transcription might not perform well...

**Comment by an-old-guy-in-Ecust** [comment]
I'm very sorry. I uploaded the wrong file. Here's my saxophone file amd harp file.
[yourmt3_saxophone_test.zip](https://github.com/user-attachments/files/18129906/yourmt3_saxophone_test.zip)
[yourmt3_harp_test.zip](https://github.com/user-attachments/files/18129913/yourmt3_harp_test.zip)

**Comment by mimbres** [comment]
@an-old-guy-in-Ecust 
Everything is clear now! The saxophone sample will have many notes due to the accompaniment, while the harp sample, being slow and with fewer notes (less than 5 within 2 seconds), explains why more notes result in slower inference speed.
