### ISSUE TITLE
no pre_coder in 'YPTF.MoE+Multi (noPS)'

### ISSUE THREAD

**Issue by kaiyolau** [mimbres/YourMT3#18]
Thanks for sharing the fantastic demo!

When I was running the collab demo using 'YPTF.MoE+Multi (noPS)', I encountered this error:
```bash
standard_env/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
TypeError: 'NoneType' object is not callable
```

on further inspection, I found that that the precoder is empty. Specifically:
```python
model.pre_coder
```

gives me:

```
Sequential(
  (0): None
)
```

Any help would be greatly appreciated!

**Comment by kaiyolau** [comment]
Just shutdown the kernel and re-run again, it works!

**Comment by mimbres** [comment]
@kaiyolau Duplicate of #15
