### ISSUE TITLE
queston about loading training dataset

### ISSUE THREAD

**Issue by Joanna1212** [mimbres/YourMT3#7]
I noticed in the code that only one dataset, such as 'commu' or 'Slakh', is loaded for training. 
How should I handle it if I want to use all datasets together for training? 🙏 thanks!

**Comment by mimbres** [comment]
@Joanna1212 
```
python train.py -d DATA_PRESET
```

- Please see `config/data_presets.py`. 
- `all_cross_final` was used for the final model training, and `all_eval_final` for test.

**Comment by Joanna1212** [comment]
thanks
